# -*- coding: utf-8 -*-
"""TFLITE_MODEL_MAKER.ipynb

Automatically generated by Colaboratory.

Original file is located at

# 새 섹션
"""

pip install tflite-model-maker

import os

import numpy as np

import tensorflow as tf
assert tf.__version__.startswith('2')

from tflite_model_maker import model_spec
from tflite_model_maker import image_classifier
from tflite_model_maker.config import ExportFormat
from tflite_model_maker.config import QuantizationConfig
from tflite_model_maker.image_classifier import DataLoader

import matplotlib.pyplot as plt

data = DataLoader.from_folder('/content/drive/MyDrive/grocery')
train_data, test_data = data.split(0.9)

print(data.gen_dataset())

model = image_classifier.create(train_data)

loss, accuracy = model.evaluate(test_data)

print('Loss: ', loss)
print('Accuracy: ', accuracy)

model.export(export_dir='/tmp/')
